server:
  port: 19991


eureka:
  instance:
    hostname: eureka1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka2:19992/eureka/,http://eureka3:19993/eureka/

  server:
    enable-self-preservation: false


spring:
  application:
    name: eureka1
