spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/taotaozhan/Spring-Cloud.git
          username: taotaozhan
          passphrase: zt521ztzhang


server:
  port: 8999

eureka:
  client:
    service-url:
    defaultZone: http://localhost:8881/eureka

